title: Eugene Chong # your name (or website title) here
logo: "/images/profile_photo2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's student in the <a href="https://www.design.upenn.edu/city-regional-planning/graduate/work">City Planning</a> and 
  <a href="https://www.design.upenn.edu/musa/about">Urban Spatial Analytics</a> programs at the University of Pennsylvania. 
  <br><br>
  Enjoys maps, transit, curb regulations, and frisbee.
  <br><br>
  <a href="https://www.linkedin.com/in/e-chong/">LinkedIn Profile</a>
  <br><br>
  <a href="https://stackoverflow.com/users/12211397/eugene-chong">StackOverflow</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here